# Generated by Django 4.2.11 on 2024-04-10 14:58

import django.core.validators
from django.db import migrations, models
import django_exam_prep_6.plant_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django_exam_prep_6.plant_app.models.only_letters])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[django_exam_prep_6.plant_app.models.first_letter_capital])),
                ('last_name', models.CharField(max_length=20, validators=[django_exam_prep_6.plant_app.models.first_letter_capital])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
