# Generated by Django 4.2.11 on 2024-04-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0002_alter_fruit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_app.profile'),
        ),
    ]
